version: "{build}"
platform: x64
image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\src-d\datasets

environment:
  GOPATH: c:\gopath

build_script:
  - go get -v github.com/src-d/datasets/PublicGitArchive/multitool
  - 7z a c:\gopath\src\github.com\src-d\datasets\multitool.windows_amd64.zip %GOPATH%\bin\multitool.exe

artifacts:
  - name: multitool.windows_amd64.zip
    path: multitool.windows_amd64.zip

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 78zsH4q19DqcpdkwnYHQoe0BakBfv+LGu1W7mXuaBC9mS87+EuAj3+yTzJv4NEfI
  artifact: multitool.windows_amd64.zip
  on:
    branch: master
    appveyor_repo_tag: true
